name: CD

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  Linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ runner.arch }}-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Package
        run: |
          # natives
          make natives
          zip -9 -r natives.zip natives

          # jar 
          mvn package
          mv target/lwjgl-zelda-triforce-1.0-SNAPSHOT.jar triforce-lwjgl.jar

          # release
          zip -9 triforce-lwjgl.zip triforce-lwjgl.jar launcher.sh

      - name: Create release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: triforce-lwjgl.zip